name: k6-load-test
on:
  push:
jobs:
  k6test:
    name: Run k6 load test
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"

    steps:
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 load test
        run: |
          ./k6 run test.js
