name: k6-load-test
on:
  workflow_dispatch:
    inputs:
      rps:
        description: "k6負荷実行のRPS"
        required: true
        default: 1000
jobs:
  k6test:
    name: Run k6 load test
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: curl nginx
        run: curl http://localhost:80
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.42.0/k6-v0.42.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Run k6 load test
        run: |
          ./k6 run simple-k6-sample.js --rps ${{ github.event.inputs.rps }}
