name: k6-load-test
on:
  push:
jobs:
  k6test:
    name: Run k6 load test
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"

    steps:
      - name: curl localhost
        run: |
          curl http://localhost:80
      - name: curl 127.0.0.1
        run: |
          curl http://127.0.0.1:80
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: simple-k6-sample.js
          flags: -u 100 --rps 10
