apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: datadog-agent
  template:
    metadata:
      labels:
        component: datadog-agent
    spec:
      containers:
        - name: datadog-agent
          # 7.4以上にするとエラーになるので一旦こちらにしています
          # https://github.com/DataDog/datadog-agent/issues/14152
          image: datadog/agent:7.39.2
          ports:
            - containerPort: 8125
          env:
            - name: DD_SITE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DD_SITE
            - name: DD_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DD_API_KEY
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "1"
